---
- name: Install Vim, Git, Docker and Docker Compose
  hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo
  tasks:
    - name: Install Git, Vim, Docker, Docker-Compose
      apt:
        name: "{{ item }}"
        state: installed
        update_cache: yes
        force_apt_get: yes
      with_items:
        - git
        - vim
        - docker
        - docker-compose
